# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Demia' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demia
 # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTBlob',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  
  
pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
 pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
 pod 'Firebase/Messaging', '~> 5.20.1'
 pod 'Firebase/Core', '~> 5.20.1'
 pod 'Firebase/Auth', '~> 5.20.1'
 pod 'Firebase/Firestore', '~> 5.20.1'
 pod 'Firebase/Storage', '~> 5.20.1'

 pod 'Stripe', '~> 14.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
